spring.application.name=auth-service
server.port=8081
spring.web.error.include-stacktrace=never
spring.web.error.include-message=always
spring.jpa.open-in-view=false

spring.datasource.url=jdbc:mysql://localhost:3307/auth_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

jwt.secret=change-this-to-a-long-random-secret-key-for-production
jwt.expiration-ms=900000
jwt.refresh-expiration-ms=604800000

api.version=1.0

springdoc.swagger-ui.persist-authorization=true
springdoc.swagger-ui.try-it-out-enabled=true

ldap.enabled=true
ldap.url=ldap://localhost:1389
ldap.base=dc=company,dc=com
ldap.admin-dn=cn=admin,dc=company,dc=com
ldap.admin-password=admin
ldap.user-ou=users

spring.docker.compose.lifecycle-management=start-and-stop
spring.docker.compose.skip.in-tests=true
